sudo: required
services:
  - docker

before_install:
  - docker build -t docker-react -f Dockerfile.dev .
  
script:
  - docker run -e CI=true docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker-react"
  env: "Dockerreact-env-1"
  bucket_name: "elasticbeanstalk-eu-west-2-532016297228"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
  
  
  

  